services:
  markupp:
    build:
      context: ./markupp
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./markupp:/src
      - markupp_data:/data
      - go_mod_cache:/go/pkg/mod

volumes:
  markupp_data:
  go_mod_cache:
